#!/usr/bin/env bash
# Run the rate-limiter benchmarks and write a markdown comparison table to
# benchmark-results.md, pivoted with scenarios as rows and algorithms as
# columns. Uses benchstat from golang.org/x/perf; no intermediate files.
#
# Install: go install golang.org/x/perf/cmd/benchstat@latest

set -euo pipefail

cd "$(dirname "$0")/.."

{
  echo '# Benchmark results'
  echo
  echo 'Generated by `scripts/bench.sh`.'
  echo
  echo '```'
  go test -bench=. -benchmem -run=^$ . 2>/dev/null |
    benchstat -row /scenario -col /algo -table sec/op,B/op -
  echo '```'
} > benchmark-results.md

echo "Wrote benchmark-results.md"
